// ALAWYS ADD "-"" INFORNT OF THE LOG
const changelogs = module.exports = [
    "-fixed spelling error in the chat command. agian > again",
    "-added a yawn command to start a chain of mass yawning",
    "-fixed userinfo bug join date undefined",
    "-Added hug command",
    "-fixed spelling error on homepage of dashboard. customisable was spelt wrong",
    "-Database issue fixed - Not loading sometimes.",
    "-Concept of banned words added.",
    "-Fixed YouTube command, not loading.",
    "-Added Changelogs to stats command.",
    "-Lockdown is being added.",
    "-Rename has been added.",
    "-Added figlet command.",
    "-Website updates!",
    "-Added blur command to image category.",
    "-Added rotate command to image category.",
    "-Added invert command to image category.",
    '-Added avatar to image category',
    '-Serverinfo added to util',
    "-Music commands are being added!",
    "-Updated userinfo command with animated emojis",
    "-Added text to emoji converter. d.emoji (text)",
    "-Fixed command handler. Moderations roles...",
    "-Guild onwers can use owner commands now",
    "-Guild owners can use Moderator commands",
    "-Fixed urban command, crashing the bot after 2024c!",
    "-Welcome message if bot joins a new guild.",
    "-Removed the last message thing(userinfo command).",
    "-Updated the command handler - Feature wise.",
    "-Added kick command - Fully working.",
    "-Added ban command - Fully working.",
    "-Fixed mute command - and showed token on stream.",
    "-Banned words are added the bot - poopoo.",
    "-Fixed database - Not much",
    "-Added game information command - d.gameinf",
    "-Added goodbye message, when member leaves.",
    "-Updated meme command, little change.",
    "-Updated avatar command, little change.",
    "-Fixed most image commands in the category.",
    "-Added warn command | Fully working with DB!",
    '-Tic Tac Toe is now a game',
    "-Stats command updated + Bug fixes",
    "-Economy system is fully added, commands left todo!",
    "-Orginised the command handler - Folder structures.",
    "-Balance command now has owner statements.",
    "-Eval command can be deleted by pressing the X.",
    "-ChangeDB command has which DB options.",
    "-Changed from pastebin to hastebin.",
    "-Connect four is now a game.",
    "-Fixed meme command.",
    "-Added slots, gunfight and Rock, paper, scissors!",
    "-work jobs now work. workid was spelling wordid",
    "-userinfo shows amount of roles",
    "-Fixed chat command, Starts and stops typing when it is supposed to.",
    "-userinfo now shows if a user is a premium member, or a developer",
    "-Whole database fixed + Removed few commands",
    "-Autorole works off of command, And only has to be set once",
    "-Fixed bannedwords so it can use a custom list<d.filter>",
    "-Fixed bot join message.",
    "-Fixed some spelling mistakes.",
    "-Added more jobs.",
    "-Added deposit and withdraw to the economy",
    "-Reworked the serverinfo command.",//Myst25.05
    "-Added the jobs, Politics, President, Queen, King",
    "-Fixed the warn system, removed unwarn ;(",
    "-Added bank interest system and a shop",
    "-Added some text lines to the cat / dog command",
    "-Switched the math command formerly using jimp to canvas",
    "-Added quote command, more features coming to this soon but the basic part is done",
    '-Added a message delete/edit logs feature',
    "-Added a blacklist to channels",
    "-Added a rob command",
    "-Added leveling system",
    "-Fixed the bug where you had to run a level command twice to setup your levels if not already",
    "-Added Screen Share Link command to miscellaneous",
    "-Fixed the bug where you only got one coin from stealing from someone.",
    "-Added a the video's thumbnail to music commands",
    "-Fixed some typos",
    "-Added a level leaderboard",
    "-Added a new fun command : **moji** Try it :D",
    "-Major improvements and fixes - Ned <3",
    "-SoundCloud is now supported as a platform for music commands.",
    "-Added this slider page thing to stats command",
    "-Added embed command - NOT FINISHED!",
    "-Check out streaming what someone's listening to through spotify using d.help play",
    "-Fixed a bug, when you first had to run d.level to create account and get actual xp",
    "-Chess is added, tell one of us if there's a bug",
    "-Combined queuetop, randomize, and queueloop into one command, the queue command",
    '-Added restart and reload command - Ned',
    '-Fixed the logs module - Ned',
    '-Moderator command up to date - Ned',
    '-Database tweaks/fixes - Ned',
    '-Added mention prefix - Ned',
    '-Fixed Docs command',
    '-Added new developer to d.devs (TheShadow#8124)',
    `-Help working with DB - Ned`,
    "-Added the growth command, go check it out!",
    "-Now able to either use a users ID, Username, Username+Discriminator or by tagging them in order to tag someone for the bot"
]
